name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    env:
        DEVELOPER_DIR: /Applications/Xcode_11.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v1
    - name: swift build
      run: |
        swift build
    - name: swift test
      run: |
        export NOTARIZE_USERNAME="{{ secret.NOTARIZE_USERNAME }}"
        export NOTARIZE_PASSWORD="{{ secret.NOTARIZE_PASSWORD }}"
        swift test
